apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-nishanth
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/nfs_clientshare
    server: 10.0.0.6
