apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    name: nginx
spec:
  containers:
    - name: nignx
      image: nignx:latest
      ports:
        - name: web
          containerPort: 80
      volumeMounts:
        - name: nfsvol
          mountPath: /usr/share/nginx/html
  volumes:
    - name: nfsvol
      persistentVolumeClaim:
        claimName: nfs-pvc-nishanth
