---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secrettest
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: secrettest
  template:
    metadata:
      labels:
        name: secrettest
    spec:
      containers:
      - name: webapp
        image: naveenmsr/envtest
        ports:
        - containerPort: 3000
        env:
        - name: LANGUAGE
          valueFrom:
            secretKeyRef:
              name: testsecret
              key: LANGUAGE
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: testsecret
              key: API_KEY