apiVersion: v1
kind: Pod
metadata:
  name: mc2
spec:
  containers:
    - name: producer1
      image: allingeek/ch6_ipc
      command: ["./ipc", "-producer"]
    - name: consumer1
      image: allingeek/ch6_ipc
      command: ["./ipc", "-consumer"]
  restartPolicy: Never
