apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: counter-pvc
  labels:
    type: local
spec:
  storageClassName: default
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
