apiVersion: v1
kind: PersistentVolume
metadata:
  name: counter-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /var/nfsshare
    server: 172.16.0.34
