apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helm
  name: helmdeploy
  namespace: default
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: helm
  template:
    metadata:
      labels:
        app: helm
    spec:
      containers:
        - name: devapp-container
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
              protocol: TCP
