apiVersion: v1
kind: Service
metadata:
  name: {{ include "httpd.fullname" . }}
  labels: 
    {{.Values.service.label }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: 
    {{ .Values.service.label }}
