apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx2
spec:
  replicas: 20
  selector:
    matchLabels:
      app: nginx2
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions: #<---- unlike nodeSelectorTerms in case of nodeAffinity, this is not a list, so the minus sign is missing here
                  - key: app
                    operator: In
                    values:
                      - nginx
      containers:
        - name: nginx
          image: nginx:1.7.9
          ports:
            - containerPort: 80
