apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidecar
spec:
  selector:
    matchLabels:
      app: 2048app
      tier: app
  replicas: 1
  template:
    metadata:
      labels:
        app: 2048app
        tier: app
    spec:
      containers:
      - name: server
        image: httpd
        ports:
          - containerPort: 80
        volumeMounts:
        - mountPath: /usr/local/apache2/htdocs/
          name: source
      - name: sync
        image: alpine/git
        command:
        - "sh"
        - "-c"
        - "git clone https://github.com/gabrielecirulli/2048 . && watch -n 30 git pull"
        workingDir: /source
        volumeMounts:
        - mountPath: /source
          name: source
      volumes:
      - emptyDir: {}
        name: source